---
title: "EEB313-Analysis"
date: "`r Sys.Date()`"
output:
  pdf_document: default
  html_document: default
---

```{r setup, message=F, echo = F}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(dplyr)
library(ggplot2)
library(maps)
library(sp)
library(sf)
library(s2)
library(rgdal)
library(mapproj)
library(urbnmapr)
library(ggfortify)
library(usethis)
library(ggmap)

```

```{r read_data}
morph <- read.csv("Morphology_metadata2.csv")
```

```{r PCA}
morph_means <- morph %>% 
  group_by(Species) %>%
  filter(!is.na(Wing) & !is.na(Culmen) & !is.na(Mass)) %>%
  summarize(mean(Wing), mean(Culmen), mean(Mass))

df <- data.frame(morph_means[,-1])

morph_pc <- prcomp(df, scale = TRUE, center = TRUE, retx = T)
summary(morph_pc)

morph_pc$rotation <- -1*morph_pc$rotation
morph_pc$rotation

autoplot(morph_pc, data = morph_means, colour = 'Species', loadings = TRUE, loadings.label = TRUE) +
labs(title = "Morph Biplot for Hawaii 'Big' Island") +
theme_classic()

plot(morph_pc)
```


```{r spatial_view, message = F}
# Identifies ESPG as 6334.
morph_sf <- st_as_sf(morph, coords = c("UTM_X", "UTM_Y"), crs = 6334)

# Transforms coordinates to standard lat-lon format.
morph_wgs84 <- st_transform(morph_sf, crs = 4326)

# Converts geometry class into separate lat-lon columns.
morph <- morph_wgs84 %>% 
  extract(geometry, c('lon', 'lat'), '\\((.*), (.*)\\)', convert = TRUE) %>% 
  as.data.frame()

# Selects for relavent columns.
morph_spa <- morph %>% 
  select(Species, Date, Sex, Wing, Culmen, Mass, lat, lon)

# Previews the data.
head(morph_spa)

# Uses ggmap to extract map of Hawaii.
map_hi <- get_map(location = 'Island of Hawaii', zoom = 9, source = "stamen", maptype = "toner-lite")

# List of natural and anthropogenic effects that can be analyzed.
effects <- list(Mauna_Loa = c(geocode("Mauna Loa"), Type = "Volcano"),
                Kīlauea = c(geocode("Kīlauea"), Type = "Volcano"),
                Hilo = c(geocode("Hilo"), Type = "Urban"),
                Waimea = c(geocode("Waimea"), Type = "Urban"),
                Kona = c(geocode("Kona"), Type = "Urban"),
                Hualalai = c(geocode("Hualalai"), Type = "Mountain"),
                Mauna_Kea = c(geocode("Mauna Kea Access Rd, Hilo, HI 96720, United States"), Type = "Mountain"),
                Pohakuloa = c(geocode("Pohakuloa Training Area"), Type = "Military"),
                Army_Reserve = c(geocode("470 W Lanikaula St, Hilo, HI 96720, United States"), Type = "Military"))

# Formats list as a dataframe.
effects <- as.data.frame(bind_rows(effects, .id = "Name"))

# Plots the data.
ggmap(map_hi) +
  geom_count(data = morph_spa, aes(x = lon, y = lat), alpha = 0.5) +
  labs(title = "Observations on \nHawaii 'Big' Island", x = "Longitude", y = "Latitude", size = "Number of \nObservations") +
  geom_point(data = effects, aes(x = lon, y = lat, shape = Type), color = "Red")

```

```{r, eval = F, include = F}
# An interactive map showing all the points.
mapview(morph_wgs84$geometry, crs= "4326", grid = FALSE)
```


